# Generated by Django 4.2.6 on 2023-11-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='customer_address',
        ),
    ]
